### ISSUE TITLE
Detectors...

### ISSUE THREAD

**Issue by andyblac** [gawindx/homebridge-risco-platform#2]
now that you have added detectors, would it be possible to get notifications from things like door sensors when they are open / closed, motion sensor when motion is detected even if if alarm is disarmed, and I have a Smoke/Heat detector could this be added to HomeKit to show status ?

**Comment by andyblac** [comment]
also atm, ALL detectors are treated as motion in HomeKit, i have magnet door sensors, could these be treated as such ?

**Comment by andyblac** [comment]
![Screenshot 2020-06-06 at 12 54 43](https://user-images.githubusercontent.com/77936/83943527-e7245c00-a7f4-11ea-9808-dd8efb37ab54.jpg)

**Comment by gawindx** [comment]
I know these limitations, all the necessary information is not in the results returned by the RiscoCloud. This requires the addition of the ability to create "custom" devices. For smoke detectors, this should be easier to implement but I have not yet taken the time to look into it (I have 2 new ones in their box that I have not yet taken the time to install them ...). your requests are therefore part of improvements planned but not yet developed.

**Comment by andyblac** [comment]
but can RiscoCloud know when a sensor is triggered even if the alarm is in "Disarm" state ?, it a shame we have no local connection to the internal IP of the panel via an API.

**Comment by gawindx** [comment]
In general, the detection of a movement goes back correctly. sometimes the trigger is too short to be displayed.

if the polling delay is too long, the information may not be returned (a delay of 10 to 15 seconds gives good results). 

it is also possible that homekit does not refresh quickly enough if the application is already open, in this case the state of the detector is not necessarily restored because it has returned to normal before the application refreshes. 
the state of exclusion (bypass) is also treated but for the moment I have not yet found how to transfer it to the accessory.

**Comment by andyblac** [comment]
so you say it should be working now ??, because i can get it to show in HomeKit nor get a notification
```
            "polling": true,
            "pollInterval": 10000,
            "Partition": "all",
            "Detectors": "all"
```

**Comment by andyblac** [comment]
```
[6/6/2020, 14:37:37] [RiscoAlarm] Detector "Front Door" => New state detected: (true). Notify!
[6/6/2020, 14:37:37] [RiscoAlarm] Detector "Front Door" => New Active state detected: (true). Notify!
[6/6/2020, 14:37:37] [RiscoAlarm] Front Door Actual State: true
[6/6/2020, 14:37:37] [RiscoAlarm] Front Door New State: false
[6/6/2020, 14:37:37] [RiscoAlarm] Front Door Identical State
[6/6/2020, 14:39:37] [RiscoAlarm] Detector "Front Door" => New state detected: (false). Notify!
[6/6/2020, 14:39:37] [RiscoAlarm] Detector "Front Door" => New Active state detected: (true). Notify!
[6/6/2020, 14:39:37] [RiscoAlarm] Front Door Actual State: true
[6/6/2020, 14:39:37] [RiscoAlarm] Front Door New State: false
[6/6/2020, 14:39:37] [RiscoAlarm] Front Door Identical State
```

don't seem to be 10 seconds ???

**Comment by andyblac** [comment]
```
[6/6/2020, 14:37:37] [RiscoAlarm] Detector "Front Door" => New state detected: (true). Notify!
[6/6/2020, 14:37:37] [RiscoAlarm] Detector "Front Door" => New Active state detected: (true). Notify!
[6/6/2020, 14:37:37] [RiscoAlarm] Front Door Actual State: true
[6/6/2020, 14:37:37] [RiscoAlarm] Front Door New State: false
[6/6/2020, 14:37:37] [RiscoAlarm] Front Door Identical State
[6/6/2020, 14:39:37] [RiscoAlarm] Detector "Front Door" => New state detected: (false). Notify!
[6/6/2020, 14:39:37] [RiscoAlarm] Detector "Front Door" => New Active state detected: (true). Notify!
[6/6/2020, 14:39:37] [RiscoAlarm] Front Door Actual State: true
[6/6/2020, 14:39:37] [RiscoAlarm] Front Door New State: false
[6/6/2020, 14:39:37] [RiscoAlarm] Front Door Identical State
```
ye it seems to take 2 mins of door open or close to detect change, and i can't get motion sensors to show any change.

**Comment by gawindx** [comment]
actually, it's weird. either I had not noticed this operation before (it seems to me, however, to have made the necessary tests), or I introduced a bug by adding the functionalities for the taking into account of the alarm. I will not be able to correct this for a few days but I am looking into it as soon as possible.

**Comment by andyblac** [comment]
np, glad i'm not going mad 😄

**Comment by gawindx** [comment]
I just published version 1.0.2 which provides support for "custom" detectors.
I advise you to look at the README for the config, but I did something simple.

Regarding the delay of the detectors, I had good test on my side but I found nothing abnormal.
In any case not in the plugin, I explain:
- The time between the actual activation of a detector and its appearance in homekit is 1 to 2 minutes BUT
- I displayed both the Homebridge and RiscoCloud web interfaces, then I now have an activated detector (by making circles in the room) and I waited for the information to appear.
The info appeared a few seconds apart (about 1-3s) on the 2 interfaces, but it took 1-2 minutes to appear, including on the RiscoCloud interface.

To be sure that this could not come from a time delay or other history on the detector, I re-tested it in the same way but this time I modified its configuration at the level of the central unit as detector "Immediate".
The observation is the same whatever the configuration of the detector.

And apart from the refreshing stories of the iOs application once opened, the info appears well at the same time on homebridge and on the iOS app.

I therefore deduce that the problem is not on my code.

**Comment by andyblac** [comment]
i'l test it, but if HomeKit only sees after 2mins then imo, motion detectors are pretty useless, as they reset before then and thus never report a motion or nor could it be used in HomeKit automations, ie turn on lights as you enter a room.

**Comment by andyblac** [comment]
installed new code, the door is detected right away, no delay, but it always shows as "Opening.." not "Open" can you fix this ?

![Screenshot 2020-06-24 at 18 38 47](https://user-images.githubusercontent.com/77936/85605455-1555c880-b64a-11ea-8c5c-cd8b0fb5eec2.jpg)

but shutting the door, dose not respond right away, so, it seems it was detect open by luck. hmmmm

**Comment by andyblac** [comment]
seems it not detecting as close, been 5 mins and it still showing as "Opening...", if this is down to Risco, then imo don't waste time on detectors, as their no use to HomeKit in this state.

**Comment by andyblac** [comment]
just done another door test, and now not detecting any change, the door has been open and HomeKit is not seeing the door as open, so 1st test was a fluke. yeah, so if you can't improve, imo don't waste your time, as it not working.

**Comment by andyblac** [comment]
also if you tap on the door sensor icon, the icon changes to "Opening..." so this what I must have done by mistake, IMO the icon should have NO user active control. are you using the correct HomeKit Accessory ???

**Comment by gawindx** [comment]
The error is corrected.
In Homekit, there is no door or window contact per se.
To have a Door or a Window with an Open / Closed state, I had to cheat a little.

Something for which I completely missed out, is that for the Doors and Windows, Homekit expects a% as a value to know if the accessory is either open / closed / being opened / being close while in the case of a Motion detector, Homekit waits for a boolean value to know if a movement is detected or not.

In fact the Homekit Door or Window accessory is more intended for, for example, a roller shutter that you could control to open it halfway (50%) or other position.

And so that the Door / Window is not indicated closing or opening, here too I had to cheat a little to indicate a target state identical to the state of the Door / Window (to make Homekit believe that the door / window movement is already finished)
Sorry...
It is corrected and updated in 1.0.4 (For 1.0.3, I accidentally left a test variable that caused a bug, so version 1.0.4 for the functional version ....)

On the other hand, the command to open or close does not act, it does not refer to anything so even if you play with it, it will not control anything (on the other hand, the requested state may remain until the application refreshes in the case of the Home iOs application).

Regarding the appearance time, I remember that some time ago this problem did not exist - moreover it is random because this afternoon, the detector of my office which I use for my tests reacted a first time very quickly (less than 15 seconds to appear on homebridge) but did it only once.

An update of the RISCOCloud is planned next week it seems to me, it is possible that this problem is corrected at the same time (or not ...).

Keep me posted if everything is good to close the issue (same for the one about the alarm trigger)

**Comment by andyblac** [comment]
installed 1.0.4, no change, it still not working here, open a door, 10 mins later, nothing noted in log, nor is it detected in HomeKit, same goes for sensors, walk around a room for 5 mins, and nothing nothing in log or in HomeKit, so if as you say it working for you, then the issue is Risco Cloud. It is just not reliable enough.

I tried restarting HomeBridge with a door open and it did detect the door open in HomeKit, but if you close the door, nothing no state change it remain open in HomeKit.

for your info my system is a LightSYS2 

for in the current state, unless Risco can fix issues, it is useless to me.

**Comment by gawindx** [comment]
i also have a lightsys so it should work.

To check, do the detectors react from the RiscoCloud web interface? or from the smartphone app?
and what is the firmware version of your control panel? is it up to date?
it could also be linked (to verify but I don't think so)?

**Comment by andyblac** [comment]
just called my engineer, he dialled in to have a look, it looks like my sensors are having issue.

`Event Supervision Loss - 'Garage', 'Garage Detector' occurred at your system at 25/06/2020 13:39:00 `

all sensors have had that today, he is going to do some calibrations tomorrow, and check firmware on panel.

it also looks like sensors are off line as I can't set the alarm atm.

**Comment by gawindx** [comment]
simple question, what are radio detectors? if so, i think it's all just the batteries that are tired.
the average lifespan of batteries on radio devices is 1 to 3 years depending on the environment and the distance.

if that's right, it will cost you a lot less to change them yourself.
And to find the version or perform the firmware update if necessary, I could perfectly tell you the method.

**Comment by andyblac** [comment]
I just changed them in FEB, he think it someone with a EF emitter, this is not the 1st time it happened.

**Comment by andyblac** [comment]
regarding firmware ye, please email me the procedure.

**Comment by andyblac** [comment]
ok, detectors are back online. it now working but with the 2 mins delay, but that is the same with Risco app too. so your right about it risco cloud issue.

![Screenshot 2020-06-25 at 20 27 56](https://user-images.githubusercontent.com/77936/85786797-82d52800-b722-11ea-8647-caf52b66b95f.jpg)

**Comment by gawindx** [comment]
it's a good thing that it works again.

I could give you the procedure to check the version tomorrow.
I will give you at the same time the procedure for the update (as well as the password and the recommendations to perform it)
on the other hand I don't think I have your email.

**Comment by andyblac** [comment]
andyblac@icloud.com

**Comment by gawindx** [comment]
Noted

I'm passing this all on to you tomorrow

**Comment by andyblac** [comment]
cheers

**Comment by andyblac** [comment]
found this in a review, it seem HomeKit support a "Contact Sensor" can you refactor "Door/Window" to this type please?

![Screenshot 2020-07-08 at 15 17 45](https://user-images.githubusercontent.com/77936/86929999-624b9b80-c12e-11ea-9ba9-e77d42286a0c.jpg)

**Comment by gawindx** [comment]
Indeed, I have since been able to get my hands on several documentations, some of which are up-to-date and directly from Apple concerning this type of device.

This will be the subject of a future update but for now I'm a bit overbooked and actively working on the permanent props issue (caching)

**Comment by andyblac** [comment]
now detectors are seen by the plugin, could you add support for that if the alarm is attempted to be set in a zone, and a contact sensor is open push a notification.

every now and again my contact sensor on the kitchen door has not registered as close in Risco Cloud or on the panel itself, as a result if you try to arm the alarm, it goes through the motions, and once it is in armed state the alarm is triggered. It would be nice that we could get a notification stating "xxxx contact sensor is open please check it" and the alarm not allow to be set.

**Comment by gawindx** [comment]
I'll see what I can do, but I don't promise I can do it quickly.

push notifications on an event I haven't yet "played" with, so I'll find out ...

**Comment by gawindx** [comment]
after several searches, it unfortunately seems that it is not natively possible to have this kind of notification.
the only possible notifications are managed directly by homekit and are those which are possible via the accessories settings in the Home application.

One possibility would be to go through a third party notification system (such as pushbullet for example), which is not the subject of this plugin.

the last published versions contain several improvements to solve this problem, like the occupancy sensor linked to the partition (does not work with groups) as well as a check of the ready state in order to validate or not the arming - for the total and partial arming, the latter being based on the assumption that the detectors are not armed in partial mode; it may therefore turn out to be inaccurate in certain cases.

not being able to provide solutions on this point, I close the issue.

However, if in the future a possibility exists or if you have an avenue of research, I would gladly look into it and integrate it if possible.
